version: "3.8"

services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - PGHOST=db
      - PGUSER=jinyuu
      - PGPASSWORD=wang20021106-+
      - PGDATABASE=jinyuu
      - PGPORT=5432

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=jinyuu
      - POSTGRES_PASSWORD=wang20021106
      - POSTGRES_DB=jinyuu
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: