# 文件名：compose-ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: compose-app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: compose.local
      http:
        paths:
          - path: /health
            pathType: Prefix
            backend:
              service:
                name: compose-app
                port:
                  number: 3000