apiVersion: v1
kind: Secret
metadata:
  name: {{ include "compose-app.fullname" . }}-secret
type: Opaque
data:
  PGUSER: {{ .Values.secret.PGUSER | b64enc | quote }}
  PGPASSWORD: {{ .Values.secret.PGPASSWORD | b64enc | quote }}
  PGDATABASE: {{ .Values.secret.PGDATABASE | b64enc | quote }}
  PGHOST: {{ .Values.secret.PGHOST | b64enc | quote }}
  PGPORT: {{ .Values.secret.PGPORT | toString | b64enc | quote }}

